// Video-capable models (Gemini only - multimodal required for YouTube URLs)
export type VideoModel =
	| "google/gemini-3-flash-preview"
	| "google/gemini-2.5-flash"
	| "google/gemini-2.0-flash-001"
	| "google/gemini-2.5-pro";

// Text models (any provider via OpenRouter)
export type TextModel =
	| VideoModel
	| "anthropic/claude-sonnet-4"
	| "anthropic/claude-haiku-4.5"
	| "openai/gpt-4.5-preview"
	| "openai/gpt-4o-mini";

// Per-operation model configuration
export interface ModelConfig {
	videoReading: VideoModel; // Must be Gemini (video-capable)
	summarization: TextModel;
	recommendationReasoning: TextModel;
	tagGeneration: TextModel;
	transcriptAnalysis: TextModel;
	memoryExtraction: TextModel;
}

// Timestamped key point from video
export interface KeyPoint {
	timestamp: string; // Format: "MM:SS" or "HH:MM:SS"
	seconds: number; // Total seconds for seeking
	title: string; // Brief title of the section
	description: string; // Detailed description of what's covered
}

// Analysis result from AI
export interface VideoAnalysis {
	summary: string; // WHAT: describes what the video is about
	reason: string; // WHY: explains why user should/shouldn't watch
	tags: string[];
	scores: {
		productivity: number;
		entertainment: number;
		educational: number;
		inspiring: number;
		creative: number;
		relevance?: number; // relevance to user interests
		// Political leaning (only present if video has political content)
		politicalX?: number; // -100 (left) to 100 (right), undefined if apolitical
		politicalY?: number; // -100 (libertarian) to 100 (authoritarian), undefined if apolitical
		hasPoliticalContent?: boolean; // explicit flag - false means truly apolitical
	};
	verdict: "worth_it" | "maybe" | "skip";
	matchesInterests?: boolean;
	enjoymentConfidence?: number; // 0-100: AI's confidence you'll enjoy based on learned preferences
	keyPoints?: KeyPoint[]; // Timestamped breakdown of key sections
	perspective?: string; // e.g., "startup founder", "academic", "critical"
}

// Cache entry with timestamp and preferences version
export interface CacheEntry {
	videoId: string;
	analysis: VideoAnalysis;
	timestamp: number;
	preferencesVersion: number; // invalidate cache when preferences change
}

// Extension settings
export interface Settings {
	apiKey: string;
	braveApiKey?: string; // Brave Search API key for related content
	models: ModelConfig; // Per-operation model selection
	cacheExpiry: number; // days
	fontSize: number; // multiplier: 0.8, 1, 1.2, 1.4, etc.
	// Personalization
	aboutMe: string; // synthesized: manual + memories
	manualPreferences: string; // user's original manual text (preserved separately)
	aboutMeAutoGenerated: boolean; // true = auto-synced with memories, false = manually edited
	// Productivity Guardian
	guardianEnabled: boolean;
	minScoreThreshold: number; // block if all scores below this
	blockedTags: string[]; // always block videos with these tags
	// Preference versioning for cache invalidation
	preferencesVersion: number;
	// Check-in prompts
	checkInEnabled: boolean; // enable/disable check-in prompts
	checkInInterval: number; // minutes between check-ins (0 = disabled)
	// Timeline markers
	showTimelineMarkers: boolean; // show chapter/note markers on progress bar
}

// Video source for memory entries (supports multiple sources after merging)
export interface VideoSource {
	videoId: string;
	videoTitle: string;
	timestamp?: number; // optional timestamp in seconds
	addedAt: number;
}

// Memory entry for learned preferences
export interface MemoryEntry {
	id: string;
	type: "like" | "dislike";
	preference: string; // what the user likes/dislikes
	confidence: number; // 0-1
	sources: VideoSource[]; // multiple sources after merging
	extractedFrom: "summary" | "content" | "tags";
	createdAt: number;
	updatedAt?: number; // tracks last merge
	// Deprecated: kept for backward compat migration
	sourceVideoId?: string;
	sourceVideoTitle?: string;
	sourceTimestamp?: number;
}

// Video feedback from user
export interface VideoFeedback {
	videoId: string;
	videoTitle: string;
	feedback: "like" | "dislike";
	analysis: VideoAnalysis;
	timestamp: number;
}

// Panel state for UI
export interface PanelState {
	status: "loading" | "partial" | "ready" | "error" | "no_key";
	videoId: string;
	analysis?: VideoAnalysis;
	error?: string;
	userFeedback?: "like" | "dislike"; // existing feedback for this video
}

// Session tracking
export interface SessionVideo {
	videoId: string;
	title: string;
	startTime: number; // when user started watching
	endTime?: number; // when user navigated away
	watchDuration?: number; // actual seconds watched (accumulated from play/pause)
	scores?: {
		productivity: number;
		educational: number;
		entertainment: number;
		inspiring: number;
		creative: number;
	};
	verdict?: "worth_it" | "maybe" | "skip";
}

export interface SessionData {
	startTime: number; // session start timestamp
	lastActivity: number; // last activity timestamp (for inactivity reset)
	videos: SessionVideo[]; // videos watched this session
	intent?: WatchIntent; // user's declared intent
	totalWatchTime?: number; // accumulated watch time in seconds
}

export type WatchIntent = "learning" | "research" | "relaxing" | "browsing";

// Channel trust tracking
export interface ChannelStats {
	channelId: string;
	channelName: string;
	videoCount: number;
	totalScores: {
		productivity: number;
		educational: number;
		entertainment: number;
		inspiring: number;
		creative: number;
	};
	avgScores: {
		productivity: number;
		educational: number;
		entertainment: number;
		inspiring: number;
		creative: number;
	};
	lastUpdated: number;
	manualTrust?: "trusted" | "blocked" | null;
}

// Liked channel tracking (channels from liked videos)
export interface LikedChannel {
	channelId: string;
	channelName: string;
	channelUrl: string;
	likedVideoIds: string[];
	likedVideoTitles: string[];
	firstLikedAt: number;
	lastLikedAt: number;
	avgScores?: {
		productivity: number;
		educational: number;
		entertainment: number;
		inspiring: number;
		creative: number;
	};
	subscriptionStatus?: "subscribed" | "not_subscribed" | "unknown";
	subscriptionCheckedAt?: number;
}

// Daily statistics
export interface DailyStats {
	date: string; // YYYY-MM-DD
	totalTime: number; // seconds
	videoCount: number;
	byCategory: {
		educational: { count: number; time: number };
		entertainment: { count: number; time: number };
		productive: { count: number; time: number };
		inspiring: { count: number; time: number };
		creative: { count: number; time: number };
	};
	avgScores: {
		productivity: number;
		educational: number;
		entertainment: number;
		inspiring: number;
		creative: number;
	};
	guardianBlocks: number;
	guardianOverrides: number;
	channelsWatched: string[]; // channel IDs
}

// Focus schedule for time-based guardian
export interface FocusPeriod {
	days: number[]; // 0-6, Sun-Sat
	startHour: number; // 0-23
	endHour: number; // 0-23
}

export interface FocusSchedule {
	enabled: boolean;
	periods: FocusPeriod[];
	focusThreshold: number; // stricter threshold during focus
	blockEntertainment: boolean;
	pausedUntil?: number; // timestamp when pause expires
}

// Related web content from Brave Search
export interface RelatedResource {
	title: string;
	url: string;
	description: string;
	source: string; // domain name
	favicon?: string;
}

export interface RelatedContentCache {
	videoId: string;
	resources: RelatedResource[];
	searchQuery: string;
	cachedAt: number;
}

// API keys (stored separately in local storage for security)
export interface ApiKeys {
	apiKey: string;
	braveApiKey?: string;
}

// User notes on videos
export interface VideoNote {
	id: string; // uuid
	videoId: string;
	videoTitle: string;
	videoUrl: string;
	timestamp: number; // seconds (video.currentTime at capture)
	timestampFormatted: string; // "2:34" or "1:02:34"
	content: string;
	createdAt: number;
	updatedAt: number;
}

// Index for notes sidebar listing
export interface NotesIndex {
	videoId: string;
	videoTitle: string;
	videoUrl: string;
	noteCount: number;
	lastNoteAt: number;
}

// Political position tracking (aggregate of all liked/disliked political content)
export interface PoliticalPosition {
	x: number; // -100 (left) to 100 (right)
	y: number; // -100 (libertarian) to 100 (authoritarian)
	sampleCount: number; // only counts videos WITH political content
	lastUpdated: number;
}

// Daily snapshot for historical political position tracking
export interface PoliticalSnapshot {
	date: string; // YYYY-MM-DD
	x: number;
	y: number;
	sampleCount: number;
	videosContributed: number; // videos that day with political content
}

// Blind spot analysis result
export interface BlindSpotAnalysis {
	narrowPerspectives: Array<{
		topic: string;
		videoCount: number;
		perspectives: string[];
		missing: string[];
	}>;
	topicCoverage: number; // 0-100%
	lastAnalyzed: number;
}
